# starship.rs
# Location: ~/.config/starship.toml

format = """
\n[╭─](#FFFFFF)\
[](#9A348E)\
$os\
$username\
$hostname\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$fossil_metrics\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$odin\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$nix_shell\
[](fg:#33658A bg:#FDFD96)\
$shell\
$shlvl\
$container\
[](fg:#FDFD96)\
$sudo\
$jobs\
$status\
$fill\
[](fg:#DA627D)\
$directory\
[ ](fg:#DA627D)\
\n$character\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[fill]
#symbol = '─'
symbol = ' '
style = 'bold white'
disabled = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#FFFFFF bg:#9A348E"
style_root = "fg:#FFFFFF bg:#9A348E"
format = '[$user ]($style)'
disabled = false

[hostname]
ssh_only = false
ssh_symbol = ' '
trim_at = ''
style = "fg:#FFFFFF bg:#9A348E"
disabled = false
format = '[$ssh_symbol](fg:#FFFF00 bg:#9A348E)[ $hostname ]($style)'

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "fg:#FFFFFF bg:#9A348E"
disabled = false

[os.symbols]
Arch = " "
Debian = " "
NixOS = " "
Kali = " "
Linux = " "
Macos = " "
Mint = "󰣭 "
Ubuntu = " "
Windows = " "

[directory]
style = "fg:#FFFFFF bg:#DA627D"
read_only_style = "fg:#FFFFFF bg:#DA627D"
format = "[ $path ]($style)[$read_only]($read_only_style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:#FFFFFF bg:#06969A"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[fennel]
symbol = " "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#FFFFFF bg:#FCA17D"
format = '[ $symbol $branch]($style)'

[git_status]
style = "fg:#FFFFFF bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'
conflicted = "  Merge conflict"
ahead = "  Ahead"
behind = "  Behind"
untracked = "  U"
modified = "  M"
staged = "  Staged"

[golang]
symbol = " "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = " "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = " "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nix_shell]
symbol = " "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol$state( \($name\)) ]($style)'

[ocaml]
symbol = " "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol($version )(\($switch_indicator$switch_name\)) ]($style)'

[odin]
symbol = "Ø "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[package]
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
symbol = " "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%r" # Hour:Minute Format
style = "fg:#FFFFFF bg:#33658A"
format = '[ $time ]($style)'

[typst]
symbol = ' '
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[zig]
symbol = '[Z]'
style = "fg:#FFFFFF bg:#86BBD8"
format = '[ $symbol($version) ]($style)'

[shell]
disabled = false
style = 'fg:#000000 bg:#FDFD96'
format = '[$indicator]($style)'
bash_indicator = '  '
fish_indicator = '  '
zsh_indicator = ' 󰬡 '
powershell_indicator = ' 󰨊 '
nu_indicator = ' nu '

[shlvl]
disabled = false
symbol = ' '
style = 'fg:#000000 bg:#FDFD96'
format = '[ $symbol$shlvl]($style)'

[sudo]
disabled = false
symbol = ''
style = 'fg:#FF0000'
format = '[ $symbol SUDO]($style)'

[jobs]
number_threshold = 1
style = "bold fg:#FFFFFF"
symbol = ' '
format = '[ $symbol$number]($style)'

[status]
disabled = false
style = "bold fg:#FFFFFF"
failure_style = "bold fg:#FF0000"
format = '[ $status]($style)'

[character]
success_symbol = '[╰─](#FFFFFF)[](#D7AFFF)[I](fg:#FFFFFF bg:#D7AFFF)[](#D7AFFF)[─](#FFFFFF)'
error_symbol = '[╰─](#FFFFFF)[](#D7AFFF)[I](fg:#FFFFFF bg:#D7AFFF)[](#D7AFFF)[─](#FF0000)'
vimcmd_symbol = '[╰─](#FFFFFF)[](#D7AFFF)[N](fg:#000000 bg:#D7AFFF)[](#D7AFFF)[─](#FFFFFF)'
vimcmd_visual_symbol = '[╰─](#FFFFFF)[](#D7AFFF)[VISUAL](fg:#000000 bg:#D7AFFF)[](#D7AFFF)[─](#FFFFFF)'
vimcmd_replace_one_symbol = '[╰─](#FFFFFF)[](#D7AFFF)[REPLACE ONE](fg:#000000 bg:#D7AFFF)[](#D7AFFF)[─](#FFFFFF)'
vimcmd_replace_symbol = '[╰─](#FFFFFF)[](#D7AFFF)[REPLACE](fg:#000000 bg:#D7AFFF)[](#D7AFFF)[─](#FFFFFF)'
